### 中转站调用成功写法
curl -i -X POST \
    'https://www.apiqik.com/gateway/v1/images/generations' \
    -H 'Authorization: Bearer QMIbErOr9HgUxzJvH17zVutWcJTsc9srOCFQlnHXbpOtCaik' \
    -H 'Content-Type: application/json' \
    --data-raw '{
      "model": "gpt-image-2",
      "background": "auto",
      "moderation": "auto",
      "n": 1,
      "output_format": "png",
      "prompt": "一只白色猫坐在窗边，柔和自然光",
      "size": "auto"
    }'

### 当前web写法
curl -i -X POST \
'https://www.apiqik.com/gateway/v1/images/generations' \
-H 'Authorization: Bearer QMIbErOr9HgUxzJvH17zVutWcJTsc9srOCFQlnHXbpOtCaik' \
-H 'Content-Type: application/json' \
--data-raw '{
    "model": "gpt-image-2",
    "prompt": "一只白色猫坐在窗边，柔和自然光",
    "n": 1,
    "size": "auto",
    "quality": "auto"
}'