package main

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"image"
	"image/color"
	"image/draw"
	_ "image/gif"
	"image/jpeg"
	_ "image/png"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"sync"
	"time"
)

const (
	defaultDownloadQuality = 95
	maxDownloadRequestSize = 64 * 1024 * 1024
	maxDownloadImageSize   = 48 * 1024 * 1024
	maxTrustedImageSources = 256
)

type imageSourceRegistry struct {
	mu      sync.RWMutex
	sources map[string]struct{}
	order   []string
}

func newImageSourceRegistry() *imageSourceRegistry {
	return &imageSourceRegistry{sources: make(map[string]struct{})}
}

func (r *imageSourceRegistry) Trust(source string) {
	if r == nil {
		return
	}

	source = strings.TrimSpace(source)
	parsed, err := url.Parse(source)
	if err != nil || parsed.Scheme != "https" || parsed.Host == "" {
		return
	}

	r.mu.Lock()
	defer r.mu.Unlock()
	if _, exists := r.sources[source]; exists {
		return
	}
	if len(r.order) >= maxTrustedImageSources {
		delete(r.sources, r.order[0])
		r.order = r.order[1:]
	}
	r.sources[source] = struct{}{}
	r.order = append(r.order, source)
}

func (r *imageSourceRegistry) Contains(source string) bool {
	if r == nil {
		return false
	}

	r.mu.RLock()
	defer r.mu.RUnlock()
	_, exists := r.sources[strings.TrimSpace(source)]
	return exists
}

func downloadImageHandler(config appConfig) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			writeJSON(w, http.StatusMethodNotAllowed, errorResponse{Error: "method not allowed"})
			return
		}

		r.Body = http.MaxBytesReader(w, r.Body, maxDownloadRequestSize)
		var input downloadImageRequest
		decoder := json.NewDecoder(r.Body)
		if err := decoder.Decode(&input); err != nil {
			writeJSON(w, http.StatusBadRequest, errorResponse{Error: "invalid json body"})
			return
		}
		if err := ensureJSONBodyEnded(decoder); err != nil {
			writeJSON(w, http.StatusBadRequest, errorResponse{Error: "invalid json body"})
			return
		}

		format := strings.ToLower(strings.TrimSpace(input.Format))
		if format != "png" && format != "jpg" {
			writeJSON(w, http.StatusBadRequest, errorResponse{Error: "format must be png or jpg"})
			return
		}

		quality := defaultDownloadQuality
		if input.Quality != nil {
			quality = *input.Quality
		}
		if quality < 1 || quality > 100 {
			writeJSON(w, http.StatusBadRequest, errorResponse{Error: "quality must be between 1 and 100"})
			return
		}

		source := strings.TrimSpace(input.Source)
		if source == "" {
			writeJSON(w, http.StatusBadRequest, errorResponse{Error: "source is required"})
			return
		}

		imageBytes, err := loadDownloadImage(source, config.ImageSourceRegistry)
		if err != nil {
			slog.Warn("image download rejected", "error", err)
			status := http.StatusBadRequest
			if !isDownloadSourceValidationError(err) {
				status = http.StatusBadGateway
			}
			writeJSON(w, status, errorResponse{Error: err.Error()})
			return
		}

		output := imageBytes
		contentType, extension, err := detectImageType(imageBytes)
		if err != nil {
			writeJSON(w, http.StatusUnsupportedMediaType, errorResponse{Error: err.Error()})
			return
		}

		if format == "jpg" {
			output, err = encodeDownloadJPEG(imageBytes, quality)
			if err != nil {
				writeJSON(w, http.StatusUnsupportedMediaType, errorResponse{Error: err.Error()})
				return
			}
			contentType = "image/jpeg"
			extension = "jpg"
		}

		w.Header().Set("Content-Type", contentType)
		w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="gpt-image.%s"`, extension))
		w.Header().Set("Content-Length", strconv.Itoa(len(output)))
		w.Header().Set("Cache-Control", "no-store")
		w.WriteHeader(http.StatusOK)
		if _, err := w.Write(output); err != nil {
			return
		}
	}
}

func ensureJSONBodyEnded(decoder *json.Decoder) error {
	var extra any
	if err := decoder.Decode(&extra); err != io.EOF {
		if err == nil {
			return fmt.Errorf("multiple json values")
		}
		return err
	}
	return nil
}

func loadDownloadImage(source string, registry *imageSourceRegistry) ([]byte, error) {
	return loadDownloadImageWithClient(source, registry, nil)
}

func loadDownloadImageWithClient(source string, registry *imageSourceRegistry, baseClient *http.Client) ([]byte, error) {
	if strings.HasPrefix(strings.ToLower(source), "data:") {
		return decodeImageDataURL(source)
	}

	if !registry.Contains(source) {
		return nil, fmt.Errorf("source URL was not generated by this backend")
	}

	return fetchExternalImageWithClient(source, source, baseClient)
}

func decodeImageDataURL(source string) ([]byte, error) {
	comma := strings.IndexByte(source, ',')
	if comma <= len("data:") {
		return nil, fmt.Errorf("invalid image data URL")
	}

	metadata := strings.Split(source[len("data:"):comma], ";")
	mediaType := strings.ToLower(strings.TrimSpace(metadata[0]))
	if !strings.HasPrefix(mediaType, "image/") {
		return nil, fmt.Errorf("image data URL must contain an image MIME type")
	}

	encoded := source[comma+1:]
	isBase64 := false
	for _, item := range metadata[1:] {
		if strings.EqualFold(strings.TrimSpace(item), "base64") {
			isBase64 = true
			break
		}
	}

	var imageBytes []byte
	var err error
	if isBase64 {
		imageBytes, err = base64.StdEncoding.DecodeString(strings.TrimSpace(encoded))
		if err != nil {
			return nil, fmt.Errorf("invalid base64 image data")
		}
	} else {
		var decoded string
		decoded, err = url.PathUnescape(encoded)
		if err != nil {
			return nil, fmt.Errorf("invalid image data URL encoding")
		}
		imageBytes = []byte(decoded)
	}

	if len(imageBytes) == 0 {
		return nil, fmt.Errorf("image data URL is empty")
	}
	if len(imageBytes) > maxDownloadImageSize {
		return nil, fmt.Errorf("image is too large")
	}

	if _, _, err := detectImageType(imageBytes); err != nil {
		return nil, fmt.Errorf("invalid image data URL: %w", err)
	}

	return imageBytes, nil
}

func fetchExternalImage(source string, endpoint string) ([]byte, error) {
	return fetchExternalImageWithClient(source, endpoint, nil)
}

func fetchExternalImageWithClient(source string, endpoint string, baseClient *http.Client) ([]byte, error) {
	endpointURL, err := url.Parse(endpoint)
	if err != nil || endpointURL.Host == "" {
		return nil, fmt.Errorf("configured image endpoint is invalid")
	}
	sourceURL, err := url.Parse(source)
	if err != nil || sourceURL.Scheme == "" || sourceURL.Host == "" {
		return nil, fmt.Errorf("source URL must be a valid HTTPS URL")
	}
	if sourceURL.Scheme != "https" || sourceURL.User != nil || sourceURL.Fragment != "" {
		return nil, fmt.Errorf("source URL must use HTTPS without credentials or fragments")
	}

	if !strings.EqualFold(sourceURL.Host, endpointURL.Host) {
		return nil, fmt.Errorf("source URL host %q is not allowed", sourceURL.Host)
	}

	request, err := http.NewRequest(http.MethodGet, sourceURL.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("create image request: %w", err)
	}

	client := &http.Client{
		Timeout: 30 * time.Second,
		CheckRedirect: func(_ *http.Request, _ []*http.Request) error {
			return fmt.Errorf("image URL redirects are not allowed")
		},
	}
	if baseClient != nil {
		client.Transport = baseClient.Transport
		client.Jar = baseClient.Jar
	}

	response, err := client.Do(request)
	if err != nil {
		return nil, fmt.Errorf("fetch source image: %w", err)
	}
	defer response.Body.Close()

	if response.StatusCode < 200 || response.StatusCode >= 300 {
		return nil, fmt.Errorf("source image returned status %d", response.StatusCode)
	}

	imageBytes, err := io.ReadAll(io.LimitReader(response.Body, maxDownloadImageSize+1))
	if err != nil {
		return nil, fmt.Errorf("read source image: %w", err)
	}
	if len(imageBytes) > maxDownloadImageSize {
		return nil, fmt.Errorf("image is too large")
	}
	return imageBytes, nil
}

func detectImageType(imageBytes []byte) (string, string, error) {
	_, format, err := image.DecodeConfig(bytes.NewReader(imageBytes))
	if err != nil {
		return "", "", fmt.Errorf("source is not a supported image")
	}

	switch format {
	case "png":
		return "image/png", "png", nil
	case "jpeg":
		return "image/jpeg", "jpg", nil
	case "gif":
		return "image/gif", "gif", nil
	default:
		return "", "", fmt.Errorf("source image format %q is not supported", format)
	}
}

func encodeDownloadJPEG(imageBytes []byte, quality int) ([]byte, error) {
	source, _, err := image.Decode(bytes.NewReader(imageBytes))
	if err != nil {
		return nil, fmt.Errorf("decode source image: %w", err)
	}

	bounds := source.Bounds()
	withWhiteBackground := image.NewRGBA(bounds)
	draw.Draw(withWhiteBackground, bounds, &image.Uniform{C: color.White}, image.Point{}, draw.Src)
	draw.Draw(withWhiteBackground, bounds, source, bounds.Min, draw.Over)

	var output bytes.Buffer
	if err := jpeg.Encode(&output, withWhiteBackground, &jpeg.Options{Quality: quality}); err != nil {
		return nil, fmt.Errorf("encode JPEG: %w", err)
	}
	return output.Bytes(), nil
}

func isDownloadSourceValidationError(err error) bool {
	message := err.Error()
	return strings.HasPrefix(message, "invalid") ||
		strings.HasPrefix(message, "image data URL") ||
		strings.HasPrefix(message, "source URL") ||
		strings.HasPrefix(message, "source URL host") ||
		strings.HasPrefix(message, "configured image endpoint") ||
		strings.HasPrefix(message, "source image host") ||
		strings.HasPrefix(message, "source image returned") ||
		strings.HasPrefix(message, "image is too large")
}
