package imageops

import (
	"bytes"
	"context"
	"encoding/base64"
	"fmt"
	"image"
	"image/color"
	"image/draw"
	_ "image/gif"
	"image/jpeg"
	"image/png"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptrace"
	"net/url"
	"strings"
	"sync"
	"time"

	_ "golang.org/x/image/webp"
)

const maxImageSize = 48 * 1024 * 1024
const externalImageTimeout = 5 * time.Minute

func DecodeDataURL(source string) ([]byte, error) {
	comma := strings.IndexByte(source, ',')
	if comma <= len("data:") {
		return nil, fmt.Errorf("invalid image data URL")
	}
	metadata := strings.Split(source[len("data:"):comma], ";")
	mediaType := strings.ToLower(strings.TrimSpace(metadata[0]))
	if !strings.HasPrefix(mediaType, "image/") {
		return nil, fmt.Errorf("image data URL must contain an image MIME type")
	}

	encoded := source[comma+1:]
	isBase64 := false
	for _, item := range metadata[1:] {
		if strings.EqualFold(strings.TrimSpace(item), "base64") {
			isBase64 = true
			break
		}
	}

	var imageBytes []byte
	var err error
	if isBase64 {
		imageBytes, err = base64.StdEncoding.DecodeString(strings.TrimSpace(encoded))
		if err != nil {
			return nil, fmt.Errorf("invalid base64 image data")
		}
	} else {
		var decoded string
		decoded, err = url.PathUnescape(encoded)
		if err != nil {
			return nil, fmt.Errorf("invalid image data URL encoding")
		}
		imageBytes = []byte(decoded)
	}

	if len(imageBytes) == 0 {
		return nil, fmt.Errorf("image data URL is empty")
	}
	if len(imageBytes) > maxImageSize {
		return nil, fmt.Errorf("image is too large")
	}
	if _, _, err := DetectType(imageBytes); err != nil {
		return nil, fmt.Errorf("invalid image data URL: %w", err)
	}
	return imageBytes, nil
}

func LoadImage(source string, registry *SourceRegistry) ([]byte, error) {
	return LoadImageWithContext(context.Background(), source, registry)
}

func LoadImageWithContext(ctx context.Context, source string, registry *SourceRegistry) ([]byte, error) {
	if strings.HasPrefix(strings.ToLower(source), "data:") {
		return DecodeDataURL(source)
	}
	if !registry.Contains(source) {
		return nil, fmt.Errorf("source URL was not generated by this backend")
	}
	return fetchExternalImage(ctx, source, source, nil)
}

func LoadImageWithClient(source string, registry *SourceRegistry, baseClient *http.Client) ([]byte, error) {
	if strings.HasPrefix(strings.ToLower(source), "data:") {
		return DecodeDataURL(source)
	}
	if !registry.Contains(source) {
		return nil, fmt.Errorf("source URL was not generated by this backend")
	}
	return FetchExternalImageWithClient(source, source, baseClient)
}

func FetchExternalImage(source, endpoint string) ([]byte, error) {
	return FetchExternalImageWithClient(source, endpoint, nil)
}

func FetchExternalImageWithClient(source, endpoint string, baseClient *http.Client) ([]byte, error) {
	return fetchExternalImage(context.Background(), source, endpoint, baseClient)
}

func fetchExternalImage(ctx context.Context, source, endpoint string, baseClient *http.Client) ([]byte, error) {
	endpointURL, err := url.Parse(endpoint)
	if err != nil || endpointURL.Host == "" {
		return nil, fmt.Errorf("configured image endpoint is invalid")
	}
	sourceURL, err := url.Parse(source)
	if err != nil || sourceURL.Scheme == "" || sourceURL.Host == "" {
		return nil, fmt.Errorf("source URL must be a valid HTTPS URL")
	}
	if sourceURL.Scheme != "https" || sourceURL.User != nil || sourceURL.Fragment != "" {
		return nil, fmt.Errorf("source URL must use HTTPS without credentials or fragments")
	}
	if !strings.EqualFold(sourceURL.Host, endpointURL.Host) {
		return nil, fmt.Errorf("source URL host %q is not allowed", sourceURL.Host)
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, sourceURL.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("create image request: %w", err)
	}
	start := time.Now()
	request = request.WithContext(httptrace.WithClientTrace(request.Context(), &httptrace.ClientTrace{
		GotFirstResponseByte: func() {
			slog.Info("source image first byte", "host", sourceURL.Hostname(), "duration_ms", time.Since(start).Milliseconds())
		},
	}))
	client := &http.Client{
		// 大图的正文传输也计入超时；后台缓存不依赖浏览器连接存活。
		Timeout: externalImageTimeout,
		CheckRedirect: func(_ *http.Request, _ []*http.Request) error {
			return fmt.Errorf("image URL redirects are not allowed")
		},
	}
	if baseClient != nil {
		client.Transport = baseClient.Transport
		client.Jar = baseClient.Jar
	}
	response, err := client.Do(request)
	if err != nil {
		return nil, fmt.Errorf("fetch source image: %w", err)
	}
	defer response.Body.Close()
	slog.Info("source image headers", "host", sourceURL.Hostname(), "status", response.StatusCode, "content_length", response.ContentLength, "content_type", response.Header.Get("Content-Type"))
	if response.StatusCode < 200 || response.StatusCode >= 300 {
		return nil, fmt.Errorf("source image returned status %d", response.StatusCode)
	}
	if response.ContentLength > maxImageSize {
		return nil, fmt.Errorf("image is too large")
	}
	if response.ContentLength >= 2*1024*1024 && strings.EqualFold(response.Header.Get("Accept-Ranges"), "bytes") {
		response.Body.Close()
		if imageBytes, rangeErr := fetchImageRanges(ctx, client, sourceURL.String(), response.ContentLength); rangeErr == nil {
			return validateFetchedImage(imageBytes, response.ContentLength, start)
		} else {
			slog.Warn("range image fetch failed; falling back to sequential download", "error", rangeErr)
		}
		request, err = http.NewRequestWithContext(ctx, http.MethodGet, sourceURL.String(), nil)
		if err != nil {
			return nil, fmt.Errorf("create image fallback request: %w", err)
		}
		response, err = client.Do(request)
		if err != nil {
			return nil, fmt.Errorf("fetch source image fallback: %w", err)
		}
		defer response.Body.Close()
	}
	imageBytes, err := io.ReadAll(io.LimitReader(response.Body, maxImageSize+1))
	if len(imageBytes) > maxImageSize {
		return nil, fmt.Errorf("image is too large")
	}
	if err != nil {
		return nil, fmt.Errorf("read source image: received %d of %d bytes after %s: %w", len(imageBytes), response.ContentLength, time.Since(start).Round(time.Millisecond), err)
	}
	if response.ContentLength >= 0 && int64(len(imageBytes)) != response.ContentLength {
		return nil, fmt.Errorf("read source image: received %d of %d bytes: %w", len(imageBytes), response.ContentLength, io.ErrUnexpectedEOF)
	}
	return validateFetchedImage(imageBytes, response.ContentLength, start)
}

func validateFetchedImage(imageBytes []byte, declaredLength int64, start time.Time) ([]byte, error) {
	if declaredLength >= 0 && int64(len(imageBytes)) != declaredLength {
		return nil, fmt.Errorf("source image body is incomplete: got %d, want %d bytes", len(imageBytes), declaredLength)
	}
	// 只缓存完整可解码的图片，不能把含有文件头或结束标记的残片当成成功结果。
	cfg, _, err := image.DecodeConfig(bytes.NewReader(imageBytes))
	if err != nil {
		return nil, fmt.Errorf("decode source image header: %w", err)
	}
	if cfg.Width <= 0 || cfg.Height <= 0 || int64(cfg.Width)*int64(cfg.Height) > 64*1024*1024 {
		return nil, fmt.Errorf("image is too large")
	}
	if _, _, err := image.Decode(bytes.NewReader(imageBytes)); err != nil {
		return nil, fmt.Errorf("decode source image: %w", err)
	}
	slog.Info("source image read complete", "bytes", len(imageBytes), "duration_ms", time.Since(start).Milliseconds())
	return imageBytes, nil
}

func fetchImageRanges(ctx context.Context, client *http.Client, source string, total int64) ([]byte, error) {
	const workers = 4
	chunkSize := (total + workers - 1) / workers
	parts := make([][]byte, workers)
	errs := make([]error, workers)
	var group sync.WaitGroup
	for index := 0; index < workers; index++ {
		index, start := index, int64(index)*chunkSize
		if start >= total {
			parts = parts[:index]
			break
		}
		end := start + chunkSize - 1
		if end >= total {
			end = total - 1
		}
		group.Add(1)
		go func() {
			defer group.Done()
			request, err := http.NewRequestWithContext(ctx, http.MethodGet, source, nil)
			if err != nil {
				errs[index] = err
				return
			}
			request.Header.Set("Range", fmt.Sprintf("bytes=%d-%d", start, end))
			response, err := client.Do(request)
			if err != nil {
				errs[index] = err
				return
			}
			defer response.Body.Close()
			if response.StatusCode != http.StatusPartialContent {
				errs[index] = fmt.Errorf("range request returned status %d", response.StatusCode)
				return
			}
			part, err := io.ReadAll(io.LimitReader(response.Body, end-start+2))
			if err != nil {
				errs[index] = err
				return
			}
			if int64(len(part)) != end-start+1 {
				errs[index] = fmt.Errorf("range body is incomplete: got %d, want %d bytes", len(part), end-start+1)
				return
			}
			parts[index] = part
		}()
	}
	group.Wait()
	for _, err := range errs {
		if err != nil {
			return nil, err
		}
	}
	imageBytes := make([]byte, 0, total)
	for _, part := range parts {
		imageBytes = append(imageBytes, part...)
	}
	if int64(len(imageBytes)) != total {
		return nil, fmt.Errorf("combined range body is incomplete: got %d, want %d bytes", len(imageBytes), total)
	}
	slog.Info("source image range fetch complete", "bytes", len(imageBytes), "parts", len(parts))
	return imageBytes, nil
}

func DetectType(imageBytes []byte) (string, string, error) {
	_, format, err := image.DecodeConfig(bytes.NewReader(imageBytes))
	if err != nil {
		return "", "", fmt.Errorf("source is not a supported image")
	}
	switch format {
	case "png":
		return "image/png", "png", nil
	case "jpeg":
		return "image/jpeg", "jpg", nil
	case "gif":
		return "image/gif", "gif", nil
	case "webp":
		return "image/webp", "webp", nil
	default:
		return "", "", fmt.Errorf("source image format %q is not supported", format)
	}
}

func EncodePNG(imageBytes []byte) ([]byte, error) {
	source, _, err := image.Decode(bytes.NewReader(imageBytes))
	if err != nil {
		return nil, fmt.Errorf("decode source image: %w", err)
	}
	var output bytes.Buffer
	if err := png.Encode(&output, source); err != nil {
		return nil, fmt.Errorf("encode PNG: %w", err)
	}
	return output.Bytes(), nil
}

func DataURL(imageBytes []byte) (string, error) {
	mime, _, err := DetectType(imageBytes)
	if err != nil {
		return "", err
	}
	return "data:" + mime + ";base64," + base64.StdEncoding.EncodeToString(imageBytes), nil
}

func EncodeJPEG(imageBytes []byte, quality int) ([]byte, error) {
	source, _, err := image.Decode(bytes.NewReader(imageBytes))
	if err != nil {
		return nil, fmt.Errorf("decode source image: %w", err)
	}
	bounds := source.Bounds()
	withWhiteBackground := image.NewRGBA(bounds)
	draw.Draw(withWhiteBackground, bounds, &image.Uniform{C: color.White}, image.Point{}, draw.Src)
	draw.Draw(withWhiteBackground, bounds, source, bounds.Min, draw.Over)
	var output bytes.Buffer
	if err := jpeg.Encode(&output, withWhiteBackground, &jpeg.Options{Quality: quality}); err != nil {
		return nil, fmt.Errorf("encode JPEG: %w", err)
	}
	return output.Bytes(), nil
}

func IsSourceValidationError(err error) bool {
	message := err.Error()
	return strings.HasPrefix(message, "invalid") ||
		strings.HasPrefix(message, "image data URL") ||
		strings.HasPrefix(message, "source URL") ||
		strings.HasPrefix(message, "source URL host") ||
		strings.HasPrefix(message, "configured image endpoint") ||
		strings.HasPrefix(message, "source image host") ||
		strings.HasPrefix(message, "source image returned") ||
		strings.HasPrefix(message, "image is too large")
}
