package imageops

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"image"
	"image/color"
	"image/draw"
	_ "image/gif"
	"image/jpeg"
	_ "image/png"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

const maxImageSize = 48 * 1024 * 1024

func DecodeDataURL(source string) ([]byte, error) {
	comma := strings.IndexByte(source, ',')
	if comma <= len("data:") {
		return nil, fmt.Errorf("invalid image data URL")
	}
	metadata := strings.Split(source[len("data:"):comma], ";")
	mediaType := strings.ToLower(strings.TrimSpace(metadata[0]))
	if !strings.HasPrefix(mediaType, "image/") {
		return nil, fmt.Errorf("image data URL must contain an image MIME type")
	}

	encoded := source[comma+1:]
	isBase64 := false
	for _, item := range metadata[1:] {
		if strings.EqualFold(strings.TrimSpace(item), "base64") {
			isBase64 = true
			break
		}
	}

	var imageBytes []byte
	var err error
	if isBase64 {
		imageBytes, err = base64.StdEncoding.DecodeString(strings.TrimSpace(encoded))
		if err != nil {
			return nil, fmt.Errorf("invalid base64 image data")
		}
	} else {
		var decoded string
		decoded, err = url.PathUnescape(encoded)
		if err != nil {
			return nil, fmt.Errorf("invalid image data URL encoding")
		}
		imageBytes = []byte(decoded)
	}

	if len(imageBytes) == 0 {
		return nil, fmt.Errorf("image data URL is empty")
	}
	if len(imageBytes) > maxImageSize {
		return nil, fmt.Errorf("image is too large")
	}
	if _, _, err := DetectType(imageBytes); err != nil {
		return nil, fmt.Errorf("invalid image data URL: %w", err)
	}
	return imageBytes, nil
}

func LoadImage(source string, registry *SourceRegistry) ([]byte, error) {
	return LoadImageWithClient(source, registry, nil)
}

func LoadImageWithClient(source string, registry *SourceRegistry, baseClient *http.Client) ([]byte, error) {
	if strings.HasPrefix(strings.ToLower(source), "data:") {
		return DecodeDataURL(source)
	}
	if !registry.Contains(source) {
		return nil, fmt.Errorf("source URL was not generated by this backend")
	}
	return FetchExternalImageWithClient(source, source, baseClient)
}

func FetchExternalImage(source, endpoint string) ([]byte, error) {
	return FetchExternalImageWithClient(source, endpoint, nil)
}

func FetchExternalImageWithClient(source, endpoint string, baseClient *http.Client) ([]byte, error) {
	endpointURL, err := url.Parse(endpoint)
	if err != nil || endpointURL.Host == "" {
		return nil, fmt.Errorf("configured image endpoint is invalid")
	}
	sourceURL, err := url.Parse(source)
	if err != nil || sourceURL.Scheme == "" || sourceURL.Host == "" {
		return nil, fmt.Errorf("source URL must be a valid HTTPS URL")
	}
	if sourceURL.Scheme != "https" || sourceURL.User != nil || sourceURL.Fragment != "" {
		return nil, fmt.Errorf("source URL must use HTTPS without credentials or fragments")
	}
	if !strings.EqualFold(sourceURL.Host, endpointURL.Host) {
		return nil, fmt.Errorf("source URL host %q is not allowed", sourceURL.Host)
	}
	request, err := http.NewRequest(http.MethodGet, sourceURL.String(), nil)
	if err != nil {
		return nil, fmt.Errorf("create image request: %w", err)
	}
	client := &http.Client{
		Timeout: 30 * time.Second,
		CheckRedirect: func(_ *http.Request, _ []*http.Request) error {
			return fmt.Errorf("image URL redirects are not allowed")
		},
	}
	if baseClient != nil {
		client.Transport = baseClient.Transport
		client.Jar = baseClient.Jar
	}
	response, err := client.Do(request)
	if err != nil {
		return nil, fmt.Errorf("fetch source image: %w", err)
	}
	defer response.Body.Close()
	if response.StatusCode < 200 || response.StatusCode >= 300 {
		return nil, fmt.Errorf("source image returned status %d", response.StatusCode)
	}
	imageBytes, err := io.ReadAll(io.LimitReader(response.Body, maxImageSize+1))
	if err != nil {
		return nil, fmt.Errorf("read source image: %w", err)
	}
	if len(imageBytes) > maxImageSize {
		return nil, fmt.Errorf("image is too large")
	}
	return imageBytes, nil
}

func DetectType(imageBytes []byte) (string, string, error) {
	_, format, err := image.DecodeConfig(bytes.NewReader(imageBytes))
	if err != nil {
		return "", "", fmt.Errorf("source is not a supported image")
	}
	switch format {
	case "png":
		return "image/png", "png", nil
	case "jpeg":
		return "image/jpeg", "jpg", nil
	case "gif":
		return "image/gif", "gif", nil
	default:
		return "", "", fmt.Errorf("source image format %q is not supported", format)
	}
}

func EncodeJPEG(imageBytes []byte, quality int) ([]byte, error) {
	source, _, err := image.Decode(bytes.NewReader(imageBytes))
	if err != nil {
		return nil, fmt.Errorf("decode source image: %w", err)
	}
	bounds := source.Bounds()
	withWhiteBackground := image.NewRGBA(bounds)
	draw.Draw(withWhiteBackground, bounds, &image.Uniform{C: color.White}, image.Point{}, draw.Src)
	draw.Draw(withWhiteBackground, bounds, source, bounds.Min, draw.Over)
	var output bytes.Buffer
	if err := jpeg.Encode(&output, withWhiteBackground, &jpeg.Options{Quality: quality}); err != nil {
		return nil, fmt.Errorf("encode JPEG: %w", err)
	}
	return output.Bytes(), nil
}

func IsSourceValidationError(err error) bool {
	message := err.Error()
	return strings.HasPrefix(message, "invalid") ||
		strings.HasPrefix(message, "image data URL") ||
		strings.HasPrefix(message, "source URL") ||
		strings.HasPrefix(message, "source URL host") ||
		strings.HasPrefix(message, "configured image endpoint") ||
		strings.HasPrefix(message, "source image host") ||
		strings.HasPrefix(message, "source image returned") ||
		strings.HasPrefix(message, "image is too large")
}
